services:
  backend:
    build: ./backend
    container_name: Backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: Frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:5173"

